---
deployment:
  tasks:
    - export REPO=/home/esubsidi/repositories/ebansos
    - /bin/cp -R $REPO/ebansos /home/esubsidi
    - /bin/cp -R $REPO/public/* /home/esubsidi/public_html
    - /bin/cp -R $REPO/vendor /home/esubsidi
    - /bin/cp $REPO/composer.json /home/esubsidi
    - /bin/cp $REPO/composer.lock /home/esubsidi
    - /bin/cp $REPO/LICENSE /home/esubsidi