---
deployment:
  tasks:
    - /bin/cp -R ebansos /home/esubsidi
    - /bin/cp -R public/* /home/esubsidi/public_html
    - /bin/cp -R vendor /home/esubsidi
    - /bin/cp composer.json /home/esubsidi
    - /bin/cp composer.lock /home/esubsidi
    - /bin/cp LICENSE /home/esubsidi